// Writes packages/nextjs/contracts/deployedContracts.ts from the latest `forge script` broadcast of
// DeployRecurringBuy on each chain: address, ABI and deployment block. `deploy:testnet` runs it after deploying.
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const broadcastDir = path.join(root, "broadcast", "DeployRecurringBuy.s.sol");
const nextjsDir = path.resolve(root, "../nextjs");
const target = path.join(nextjsDir, "contracts", "deployedContracts.ts");

/** { chainId: { contractName: { address, abi, inheritedFunctions, deployedOnBlock } } } */
function readDeployments(getAddress) {
  const deployments = {};
  if (!fs.existsSync(broadcastDir)) return deployments;
  for (const chainId of fs.readdirSync(broadcastDir)) {
    const runFile = path.join(broadcastDir, chainId, "run-latest.json");
    if (!/^\d+$/.test(chainId) || !fs.existsSync(runFile)) continue;
    const { transactions, receipts } = JSON.parse(fs.readFileSync(runFile, "utf8"));
    const contracts = {};
    for (const tx of transactions) {
      if (tx.transactionType !== "CREATE" || !tx.contractName) continue;
      const receipt = receipts.find(r => r.transactionHash === tx.hash);
      if (receipt?.status !== "0x1") continue;
      const artifact = path.join(root, "out", `${tx.contractName}.sol`, `${tx.contractName}.json`);
      const { abi } = JSON.parse(fs.readFileSync(artifact, "utf8"));
      contracts[tx.contractName] = {
        address: getAddress(tx.contractAddress),
        abi,
        inheritedFunctions: {},
        deployedOnBlock: Number(receipt.blockNumber),
      };
    }
    if (Object.keys(contracts).length > 0) deployments[chainId] = contracts;
  }
  return deployments;
}

if (!fs.existsSync(nextjsDir)) {
  console.log("No packages/nextjs in this project: nothing to write.");
} else {
  // The app's own viem checksums the addresses and its prettier formats the file.
  const requireFromApp = createRequire(path.join(nextjsDir, "package.json"));
  const { getAddress } = requireFromApp("viem");
  const prettier = requireFromApp("prettier");
  const chains = Object.entries(readDeployments(getAddress))
    .map(([chainId, contracts]) => `${chainId}: ${JSON.stringify(contracts, null, 2)},`)
    .join("\n");
  const source = `/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {${chains}} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;
  fs.writeFileSync(target, await prettier.format(source, { parser: "typescript" }));
  console.log(`Updated ${path.relative(path.resolve(root, "../.."), target)}`);
}
